package pokemonFight.controller;

import pokemonFight.manager.pojo.Attack;

public class AttackController {
	Attack vineWhip = new Attack("Látigo cepa", 45, 100);
	Attack tackle = new Attack("Placaje", 40, 100);
	Attack flamethrower = new Attack("Lanzallamas", 90, 100);
	Attack scratch = new Attack("Arañazo", 40, 100);
	Attack waterGun = new Attack("Pistola agua", 40, 100);
	Attack bite = new Attack("Mordisco", 70, 100);
	Attack crunch = new Attack("Triturar", 100, 100);
	Attack quickAttack = new Attack("At. rapido", 40, 100);
	Attack thunderbolt = new Attack("Rayo", 60, 100);
	Attack ironTail = new Attack("Cola ferrea", 80, 100);
	Attack hyperBeam = new Attack("Hiperrayo", 110, 90);
	Attack solarBeam = new Attack("Rayo solar", 100, 90);
	Attack iceBeam = new Attack("Rayo hielo", 90, 100);
	Attack psychic = new Attack("Psiquico", 90, 100);
	Attack rockSlide = new Attack("Rock Slide", 75, 90);
	Attack earthquake = new Attack("Terremoto", 100, 100);
	Attack thunder = new Attack("Trueno", 110, 70);
	Attack blizzard = new Attack("Ventisca", 110, 70);
	Attack shadowBall = new Attack("Bola sombra", 80, 100);
	Attack dragonClaw = new Attack("Garra dragon", 80, 100);
	Attack darkPulse = new Attack("Pulso umbrio", 80, 100);
	Attack sludgeBomb = new Attack("Bomba lodo", 90, 100);
	Attack fireBlast = new Attack("LLamarada", 110, 85);
	Attack surf = new Attack("Surf", 90, 100);
	Attack airSlash = new Attack("Corte aereo", 90, 95);
	Attack brickBreak = new Attack("Abocajarro", 100, 100);
	Attack bugBuzz = new Attack("Estoicismo", 70, 100);
	Attack bodySlam = new Attack("Golpe cuerpo", 85, 100);
	Attack megaPunch = new Attack("Megapuño", 80, 85);
	Attack razorLeaf = new Attack("Hoja afilada", 55, 95);
	Attack thunderShock = new Attack("Impactrueno", 40, 100);
	Attack ember = new Attack("Ascuas", 40, 100);
	Attack swift = new Attack("Rapidez", 60, 1000);
	Attack hydroPump = new Attack("Hidrobomba", 110, 80);
	Attack fly = new Attack("Vuelo", 90, 95);
	Attack fireSpin = new Attack("Giro fuego", 35, 85);
	Attack dig = new Attack("Excavar", 80, 100);
	Attack doubleEdge = new Attack("Doble filo", 120, 100);
	Attack megaKick = new Attack("Megapatada", 120, 75);
	Attack strength = new Attack("Fuerza", 80, 100);
	Attack submission = new Attack("Sumisión", 80, 80);
	Attack seismicToss = new Attack("Movimiento sísmico", 80, 100);
	Attack solarBlade = new Attack("Cuchillada solar", 125, 100);
	Attack magicalLeaf = new Attack("Hoja mágica", 60, 1000);
	Attack confusion = new Attack("Confusión", 50, 100);
	Attack psywave = new Attack("Psicoonda", 80, 100);
	Attack teleport = new Attack("Teletransporte", 0, 100);
	Attack futureSight = new Attack("Premonición", 120, 65);
}